# X-Plane Connection Settings
xplane_api:
  web_api_http_url:       "http://127.0.0.1:8086/api/v2"
  web_api_websocket_url:  "ws://127.0.0.1:8086/api/v2"

# ATC Settings
atc:
  message_buffer_size:    10
  listen_all_frequencies: true
  strcit_flightplan_matching: false
  airlines_file:     "resources/airlines.json"
  atc_data_file:     "/home/dmorris/decimal-niner/X-Plane/atc.dat"
  atc_regions_file:  "/home/dmorris/decimal-niner/X-Plane/atc_regions.dat"
  #airports_data_file:   "/home/dmorris/decimal-niner/X-Plane/apt.min.dat"  # minimal for development speed
  airports_data_file:       "/home/dmorris/decimal-niner/X-Plane/apt.dat"   # full file - slow 
  voices:
    phrases_file:       "resources/phrases.json"
    unicom_phrases_file: "resources/phrases_unicom.json"
    sox:
      application: "/usr/bin/play"
    piper:
      application:        "/home/dmorris/.local/bin/piper"
      voice_directory:    "/home/dmorris/piper-voices"
trafficglobal:
  bgl_file: "/home/dmorris/decimal-niner/X-Plane/Traffic_Global_Airlines.bgl"
  #bgl_file: "/home/dmorris/decimal-niner/X-Plane/Traffic_Sample.bgl"