# X-Plane Connection Settings
xplane:
  web_api_http_url:       "http://127.0.0.1:8086/api/v2"
  web_api_websocket_url:  "ws://127.0.0.1:8086/api/v2"
  application_path:       ""

# ATC Settings
atc:
  message_buffer_size:    5
  voices:
    phrases_file:       "/home/dmorris/decimal-niner/resources/phrases.json"
    sox:
      application: "/usr/bin/play"
    piper:
      application:        "/home/dmorris/piper/piper"
      voice_directory:    "/home/dmorris/piper-voices"
